// WARNING: This file is generated by ngpathway module and should not be modified manually.
import { Route } from '@angular/router';
import { DashboardPageComponent } from 'src/pages/dashboard-page.component';

export const ROUTES: Route[] = [
    {
        path: '',
        component: DashboardPageComponent
    },
];