// WARNING: This file is generated by ngpathway module and should not be modified manually.
import { Route } from '@angular/router';
import { ProductPageComponent } from 'src/pages/Products/product-page.component';

export const ROUTES: Route[] = [
    {
        path: '',
        component: ProductPageComponent
    },
];