// WARNING: This file is generated by ngpathway module and should not be modified manually.
import { Route } from '@angular/router';
import { TeamsCatalogPageComponent } from 'src/pages/Teams/teams-catalog-page.component';
import { TeamDetailsLayoutComponent } from 'src/pages/Teams/[id]/(team-details)/team-details-layout.component';
import { TeamOverviewPageComponent } from 'src/pages/Teams/[id]/team-overview-page.component';

export const ROUTES: Route[] = [
    {
        path: '',
        component: TeamsCatalogPageComponent
    },
    {
        path: ':id',
        component: TeamDetailsLayoutComponent,
        children: [
            {
                path: '',
                component: TeamOverviewPageComponent
            },
        ]
    },
];