// WARNING: This file is generated by ngpathway module and should not be modified manually.
import { Route } from '@angular/router';

export const routes: Route[] = __ROUTES__.map(({ path, module }) => {
  return {
    path,
    loadChildren: () => import(`./router/${module}`).then((mod) => mod.ROUTES)
  };
});
